name = "DFControl"
uuid = "1e31e15d-4957-550d-a244-318eced754ae"
authors = ["Louis Ponet <louisponet@gmail.com>"]
repo = "https://github.com/louisponet/DFControl.jl.git"
version = "0.1.1"

[deps]
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"
StaticArrays = "90137ffa-7385-5640-81b9-e52037218182"
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Crayons = "a8cc5b0e-0ffa-5ad4-8c14-923d3ee1735f"
Requires = "ae029012-a4dd-5104-9daa-d747884805df"
Media = "e89f7d12-3494-54d1-8411-f7d8b9ae1f27"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
[compat]
Plots = ">=0.17.3"

[extras]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
Suppressor = "fd094767-a336-5f1f-9728-57cf17d0bbfb"

[targets]
test = ["Plots", "Test", "Suppressor"]
