name = "DFControl"
uuid = "1e31e15d-4957-550d-a244-318eced754ae"
authors = ["Louis Ponet <louisponet@gmail.com>"]
repo = "https://github.com/louisponet/DFControl.jl.git"
version = "0.1.1"

[deps]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Compat = "34da2185-b29b-5c13-b0c7-acf172513d20"
Conda = "8f4d0f93-b110-5947-807f-2305c1781a2d"
GeometryTypes = "4d00f742-c7ba-57c2-abde-4428a4b178cb"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Media = "e89f7d12-3494-54d1-8411-f7d8b9ae1f27"
Nullables = "4d1e1d77-625e-5b40-9113-a560ec7a8ecd"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
RecipesBase = "3cdcf5f2-1ef4-517c-9805-6587b60abb01"

[compat]
Plots = "0.17.3+"

[extras]
BinDeps = "9e28174c-4ba2-5203-b857-d8d62c4213ee"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"

[targets]
build = ["BinDeps"]
test = ["Plots"]
