[deps]
DFControl = "1e31e15d-4957-550d-a244-318eced754ae"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
LibGit2 = "76f85450-5226-5b5a-8eaa-529ad045b433"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Pkg = "44cfe95a-1eb2-52ea-b672-e2afdf69b78f"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
